---
- name: import check os
  import_tasks: check_os.yml
  tags:
    - always

- name: import centos prerequisites
  import_tasks: centos_prerequisites.yml
  tags:
    - always

- name: import postgresql install
  import_tasks: psql_install.yaml
  tags:
    - install

- name: import postgresql init
  import_tasks: psql_init.yml

- name: import postgresql backup
  import_tasks: psql_backup.yml
  tags:
    - always

- name: import postgres firewall
  import_tasks: psql_firewall.yml
  tags:
    - always
