---
- name: postgres initialize databases
  command: "postgresql-{{ postgres_version }}-setup initdb"
  listen: 'postgres init db'

- name: restart postgresql
  service:
    name: "postgresql-{{ postgres_version }}"
    state: restarted
    enabled: yes
  listen: 'postgres init db'
